---
title: "Assignment 1: Introduction"
author: "Fiona Price"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have some R experience and extensive Xcel experience. I taught myself R for a research project during college. I can do data cleaning and some data analyses (such as linear regressions) and can create a variety of graphs. However, since my R training was never formal I am not very confident in my abilities. I used Xcel for my consulting job last year; I worked with rather large data sets and learned how to clean my data and index match. 

2. Are there any components of the course about which you feel confident?

> Answer: As mentioned above, I do have some knowledge of R, so I feel confident in some of those abilities. I worked with very large and complex biodiversity monitoring datasets, which taught me the importance of data cleaning. I was also able to create some fairly complex graphs and maps. I feel pretty comfortable using ggplot (especially playing around with the colors (I love the wes anderson package)).

3. Are there any components of the course about which you feel apprehensive?

> Answer: I feel most apprehensive about just keeping my data organized. Because I did not formally learn R, I really just kept my code in random places. I have no prior knowledge of github, which I think will be hard for me to adjust to but greatly helpful in the long run! I am also nervous for the coding assignments later in the term, as I have very little coding knowledge. It's hard for me to look at data and think of how best to go about starting analyses, but I know I will learn these skills in this class. I'm excited to learn!

## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account.

> Answer: https://github.com/feeprice/EDE_Fall2024

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
